config-sparse:
  modules:
    ucp2-legacy:
      config:
        ai_access:
          enabled:
            contents:
              suggested-value: true
        ai_assaultswitch:
          enabled:
            contents:
              suggested-value: true
        ai_buywood:
          enabled:
            contents:
              suggested-value: true
        ai_defense:
          enabled:
            contents:
              suggested-value: true
        ai_fix_crusader_archers_pitch:
          enabled:
            contents:
              suggested-value: true
        ai_fix_laddermen_with_enclosed_keep:
          enabled:
            contents:
              suggested-value: true
        ai_nosleep:
          enabled:
            contents:
              suggested-value: true
        ai_rebuild:
          enabled:
            contents:
              suggested-value: true
        ai_tethers:
          enabled:
            contents:
              suggested-value: true
        ai_towerengines:
          enabled:
            contents:
              suggested-value: true
        ai_housing:
          build_housing:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 5
          campfire_housing:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 10
          delete_housing:
            enabled:
              contents:
                suggested-value: true
        ai_resources_rebuy:
          flour:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 36
          iron:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 36
          wood:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 36
        ai_demolish:
          ai_demolish_eco:
            enabled:
              contents:
                suggested-value: true
          ai_demolish_trapped:
            enabled:
              contents:
                suggested-value: true
          ai_demolish_walls:
            enabled:
              contents:
                suggested-value: true
        ai_addattack:
          contents:
            suggested-value:
              enabled: true
              choice: relative
              choices:
                absolute:
                  slider: 5
                relative:
                  slider: 1
        ai_attacklimit:
          contents:
            suggested-value:
              enabled: true
              sliderValue: 3000
        ai_attackwave:
          contents:
            suggested-value:
              enabled: true
              sliderValue: 15
        ai_recruitstate_initialtimer:
          contents:
            suggested-value:
              enabled: true
              sliderValue: 0
        fix_apple_orchard_build_size:
          enabled:
            contents:
              suggested-value: true
        o_freetrader:
          enabled:
            contents:
              suggested-value: true
        o_healer:
          enabled:
            contents:
              suggested-value: true
        o_responsivegates:
          enabled:
            contents:
              suggested-value: true
        o_firecooldown:
          contents:
            suggested-value:
              enabled: false
              sliderValue: 2000
        u_arabwall:
          enabled:
            contents:
              suggested-value: true
        u_arabxbow:
          enabled:
            contents:
              suggested-value: true
        u_laddermen:
          enabled:
            contents:
              suggested-value: true
        u_spearmen:
          enabled:
            contents:
              suggested-value: true
        u_spearmen_run:
          enabled:
            contents:
              suggested-value: true
        o_fix_map_sending:
          enabled:
            contents:
              suggested-value: true
        o_fix_rapid_deletion_bug:
          enabled:
            contents:
              suggested-value: true
        o_fix_baker_disappear:
          enabled:
            contents:
              suggested-value: true
        o_fix_fletcher_bug:
          enabled:
            contents:
              suggested-value: true
        o_fix_ladderclimb:
          enabled:
            contents:
              suggested-value: true
        o_fix_moat_digging_unit_disappearing:
          enabled:
            contents:
              suggested-value: true
        o_restore_arabian_engineer_speech:
          enabled:
            contents:
              suggested-value: true
        u_fireballistafix:
          enabled:
            contents:
              suggested-value: true
        u_fix_applefarm_blocking:
          enabled:
            contents:
              suggested-value: true
        u_fix_lord_animation_stuck_movement:
          enabled:
            contents:
              suggested-value: true
        u_tanner_fix:
          enabled:
            contents:
              suggested-value: true
        o_increase_path_update_tick_rate:
          enabled:
            contents:
              suggested-value: true
        o_change_siege_engine_spawn_position_catapult:
          enabled:
            contents:
              suggested-value: true
        o_onlyai:
          enabled:
            contents:
              suggested-value: true
        o_override_identity_menu:
          enabled:
            contents:
              suggested-value: true
        o_xtreme:
          enabled:
            contents:
              suggested-value: true
        o_stop_player_keep_rotation:
          enabled:
            contents:
              suggested-value: false
        o_moatvisibility:
          enabled:
            contents:
              suggested-value: true
        o_gamespeed:
          enabled:
            contents:
              suggested-value: true
        o_engineertent:
          enabled:
            contents:
              suggested-value: true
        o_default_multiplayer_speed:
          contents:
            suggested-value:
              enabled: true
              sliderValue: 50
        o_fast_placing:
          enabled:
            contents:
              suggested-value: true
        o_armory_marketplace_weapon_order_fix:
          enabled:
            contents:
              suggested-value: true
    graphicsApiReplacer:
      config:
        graphic:
          vsync:
            contents:
              suggested-value: true
    startResources:
      config:
        startGold:
          normal:
            noAdvantage:
              human:
                contents:
                  suggested-value: 2000
              computer:
                contents:
                  suggested-value: 2000
            majorHumanAdvantage:
              computer:
                contents:
                  suggested-value: 1000
              human:
                contents:
                  suggested-value: 1000
            minorHumanAdvantage:
              computer:
                contents:
                  suggested-value: 500
              human:
                contents:
                  suggested-value: 500
            minorComputerAdvantage:
              computer:
                contents:
                  suggested-value: 4000
            majorComputerAdvantage:
              computer:
                contents:
                  suggested-value: 8000
              human:
                contents:
                  suggested-value: 2000
          crusader:
            majorHumanAdvantage:
              computer:
                contents:
                  suggested-value: 1000
              human:
                contents:
                  suggested-value: 1000
            minorHumanAdvantage:
              computer:
                contents:
                  suggested-value: 500
              human:
                contents:
                  suggested-value: 500
            noAdvantage:
              computer:
                contents:
                  suggested-value: 2000
              human:
                contents:
                  suggested-value: 2000
            minorComputerAdvantage:
              human:
                contents:
                  suggested-value: 2000
              computer:
                contents:
                  suggested-value: 4000
            majorComputerAdvantage:
              human:
                contents:
                  suggested-value: 2000
              computer:
                contents:
                  suggested-value: 8000
        startGoods:
          normal:
            iron:
              contents:
                suggested-value: 10
            bread:
              contents:
                suggested-value: 15
            cheese:
              contents:
                suggested-value: 15
            meat:
              contents:
                suggested-value: 15
            fruit:
              contents:
                suggested-value: 15
          crusader:
            iron:
              contents:
                suggested-value: 10
            bread:
              contents:
                suggested-value: 15
            cheese:
              contents:
                suggested-value: 15
            meat:
              contents:
                suggested-value: 15
            fruit:
              contents:
                suggested-value: 15
  plugins: {}
meta:
  version: 1.0.0
